# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineral',
            name='group',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
